# Generated by Django 3.0.3 on 2020-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tododone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoDone',
        ),
        migrations.AddField(
            model_name='todo',
            name='clicked',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
